# Generated by Django 4.2.7 on 2023-11-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_roll', models.IntegerField()),
                ('employee_city', models.CharField(max_length=100)),
            ],
        ),
    ]
